In [ ]:
import logging
import warnings
import random
from tqdm import tqdm
from collections import Counter

import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from torch.utils.data import Dataset

import os


import transformers
from transformers.modeling_outputs import SequenceClassifierOutput
from transformers import (
    BertTokenizer,
    BertModel,
    PretrainedConfig,
    PreTrainedModel,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)


from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_recall_fscore_support,
    accuracy_score,
    confusion_matrix
)

from huggingface_hub import HfApi, create_repo

warnings.filterwarnings("ignore", category=FutureWarning, module="transformers.tokenization_utils_base")
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning)

loggers = [logging.getLogger(name) for name in logging.root.manager.loggerDict]
for logger in loggers:
    if "transformers" in logger.name.lower():
        logger.setLevel(logging.ERROR)

torch.set_default_tensor_type(torch.FloatTensor)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

aspects = ['appearance', 'aroma', 'palate', 'taste']

def set_random_set(seed):
    transformers.set_seed(seed)  # For transformers
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    random.seed(seed)
    np.random.seed(seed)

set_random_set(2024)

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
vocab_size = tokenizer.vocab_size
bert = BertModel.from_pretrained('bert-base-uncased')
hf_token = ""
del tokenizer, bert # only download for cached
torch.cuda.empty_cache()

2025-09-17 01:56:02.700772: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1758074162.899337      19 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1758074162.951631      19 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [2]:
class BeerReviewDataset(Dataset):
    def __init__(self, ids, absa_1, absa_2, attention_masks, token_type_ids, labels):
        self.ids = ids
        self.absa_1 = absa_1
        self.absa_2 = absa_2
        self.attention_masks = attention_masks
        self.token_type_ids = token_type_ids
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            'input_ids': self.ids[idx],
            'absa_1': self.absa_1[idx],
            'absa_2': self.absa_2[idx],
            'attention_mask': self.attention_masks[idx],
            'token_type_ids': self.token_type_ids[idx],
            'labels': self.labels[idx]
        }

In [3]:
class BERTConfig(PretrainedConfig):
    model_type = "bert_with_absa"

    def __init__(self, absa_method=None, num_classes=2, class_weight=None, **kwargs):
        super().__init__(**kwargs)
        self.absa_method = absa_method
        self.num_classes = num_classes
        self.class_weight = class_weight

class InnerBert(nn.Module):
    def __init__(self, num_classes):
        super(InnerBert, self).__init__()
        self.bert = BertModel.from_pretrained('bert-base-uncased')
        self.dropout = nn.Dropout(0.3)
        self.fc = nn.Linear(768, num_classes)
        

    def forward(self, inputs_embeds=None, attention_mask=None, token_type_ids=None):      
        _, pooled_output = self.bert(inputs_embeds=inputs_embeds, attention_mask=attention_mask, token_type_ids=token_type_ids, return_dict=False)
        x = self.dropout(pooled_output)
        logits = self.fc(x)

        return logits

class BERTModel(PreTrainedModel):
    config_class = BERTConfig

    def __init__(self, config):
        super().__init__(config)
        self.num_classes = config.num_classes
        self.absa_method = config.absa_method
        
        self.bert_sent = InnerBert(self.num_classes)

        if self.absa_method:
            self.absa_fc = nn.Linear(1, 768)
            self.bert_absa = InnerBert(self.num_classes)

        if config.class_weight is not None:
            class_weight = torch.tensor(config.class_weight, dtype=torch.float32)
            self.criterion = nn.CrossEntropyLoss(weight=class_weight.to(device))
        else:
            self.criterion = nn.CrossEntropyLoss()

        self.init_weights()


    def forward(self, input_ids=None, absa_1=None, absa_2=None, attention_mask=None, token_type_ids=None, labels=None):
        inputs_embeds = self.bert_sent.bert.embeddings(input_ids=input_ids, token_type_ids=token_type_ids)
        logits_sent = self.bert_sent(inputs_embeds, attention_mask, token_type_ids)
        
        if self.absa_method:
            absa_1 = self.absa_fc(absa_1)
            absa_2 = self.absa_fc(absa_2)
            absa_concat = torch.cat((absa_1, absa_2), dim=1)
            token_type_ids_absa = torch.tensor([0, 1]).unsqueeze(0).repeat(absa_concat.shape[0], 1).to("cuda")
            
            logits_absa = self.bert_absa(absa_concat, None, token_type_ids_absa)
            
            logits_sent += logits_absa
        
        loss = None
        if labels is not None:
            loss = self.criterion(logits_sent, labels)
    
        return SequenceClassifierOutput(loss=loss, logits=logits_sent)

In [4]:
def train_and_eval_model(aspect, method, absa_method, model, train_dataset, val_dataset, test_dataset, val_null_count, batch_size, num_epochs, lr, weight_decay=0.01, patience=5):

    model_id = f"trungpq/rlcc-new-{aspect}-{method}-absa-{absa_method}"
    try:
        repo_info = HfApi().repo_info(repo_id=model_id, token=hf_token)
    except Exception as e:
        if "404" in str(e):  # If repo does not exist
            create_repo(model_id, token=hf_token)
        else:
            print(f"An error occurred: {e}")
    
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = torch.argmax(torch.tensor(logits), dim=1).numpy()
        labels = labels.flatten()
    
        # if val_null_count > 0:
        #     null_preds = np.full(val_null_count, 3)
        #     null_labels = np.full(val_null_count, 3)
        #     preds = np.concatenate([preds, null_preds])
        #     labels = np.concatenate([labels, null_labels])
    
        # --- macro ---
        precision_macro, recall_macro, f1_macro, _ = precision_recall_fscore_support(
            labels, preds, average="macro"
        )
        # --- micro ---
        precision_micro, recall_micro, f1_micro, _ = precision_recall_fscore_support(
            labels, preds, average="micro"
        )
    
        cm = confusion_matrix(labels, preds)
    
        tp = np.diag(cm)
        fp = cm.sum(axis=0) - tp
        fn = cm.sum(axis=1) - tp
        tn = cm.sum() - (tp + fp + fn)
    
        total_tp = tp.sum()
        total_fp = fp.sum()
        total_fn = fn.sum()
        total_tn = tn.sum()
    
        return {
            "accuracy": accuracy_score(labels, preds),
            "f1_macro": f1_macro,
            "precision_macro": precision_macro,
            "recall_macro": recall_macro,
            "f1_micro": f1_micro,
            "precision_micro": precision_micro,
            "recall_micro": recall_micro,
            "total_tf": [total_tp, total_fp, total_tn, total_fn],
        }


    num_warmup_steps = int(len(train_dataset) / batch_size)
    num_logging_steps = int(num_warmup_steps / 5)
    if num_logging_steps == 0:
        num_logging_steps = 1

    training_args = TrainingArguments(
        output_dir=f"./reviews/results/{aspect}/",
        eval_strategy="epoch",   
        save_strategy="epoch",
        learning_rate=lr,
        max_grad_norm=1.0,
        warmup_steps=num_warmup_steps,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        num_train_epochs=num_epochs,
        weight_decay=weight_decay,
        load_best_model_at_end=True,  # For early stopping
        metric_for_best_model="eval_f1_macro",
        greater_is_better=True,
        save_total_limit=1,  # Limit to save the best model only
        logging_dir='./logs',
        logging_steps=num_logging_steps,
        save_steps=10,
        report_to="none",
        disable_tqdm=False,
        push_to_hub=False,
        hub_model_id=model_id,
        hub_token=hf_token
    )

    early_stopping_callback = EarlyStoppingCallback(
        early_stopping_patience=patience,
        early_stopping_threshold=0.005  # Minimum change to qualify as an improvement
    )

    # Initialize Trainer with model, arguments, train and evaluation datasets, and metrics
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics,
        callbacks=[early_stopping_callback]
    )

    # Train the model
    trainer.train()
    trainer.push_to_hub()
    
    # tạo folder nếu chưa có
    os.makedirs("phase2_log", exist_ok=True)
    
    history = pd.DataFrame(trainer.state.log_history)
    history.to_csv(f"phase2_log/{aspect}_{method}_{absa_method}.csv", index=False)
    
    torch.cuda.empty_cache()

    trainer = Trainer(
        model=model,
        args=training_args,
        eval_dataset=test_dataset,
        compute_metrics=compute_metrics
    )

   # Evaluate the model
    torch.cuda.empty_cache()
    eval_results = trainer.evaluate()
    print(f"Test results: {eval_results}")

    # --- bổ sung labels/preds ---
    logits, labels = trainer.predict(test_dataset)[:2]
    preds = torch.argmax(torch.tensor(logits), dim=1).numpy()
    eval_results["eval_labels"] = labels.tolist()
    eval_results["eval_preds"] = preds.tolist()

    del trainer
    return eval_results

In [5]:
from datasets import load_dataset

def _truncate_seq_pair(tokens_a, tokens_b, max_length):
    """Truncates a sequence pair in place to the maximum length."""

    while True:
        total_length = len(tokens_a) + len(tokens_b)
        if total_length <= max_length:
            break
        if len(tokens_a) > len(tokens_b):
            tokens_a.pop()
        else:
            tokens_b.pop()

def get_dataset(aspect, method, absa_method, tokenizer, set_name, device='cuda', upsampling_time=5):

    if not absa_method:
        absa_method = "min"
    
    df = load_dataset(f"trungpq/rlcc-new-data-{aspect}")[set_name].to_pandas()
    df = df[['sentences_1', f'absa_{absa_method}_1', 'sentences_2', f'absa_{absa_method}_2', aspect]]
    if set_name == "train":
        df.dropna(inplace=True)

    labels = np.where(
        df[aspect].isnull(),
        3,
        df[aspect].replace({-1: 0, 0: 1, 1: 2}).values
    )
    null_count = (labels == 3).sum().item()
    
    df.dropna(inplace=True)
    # df = df.sample(n=100)

    sent_1 = df['sentences_1'].astype(str).to_list()
    sent_2 = df['sentences_2'].astype(str).to_list()

    absa_1 = df[f'absa_{absa_method}_1'].astype(float).to_list()
    absa_2 = df[f'absa_{absa_method}_2'].astype(float).to_list()

    absa_1 = torch.tensor(absa_1, dtype=torch.float32).unsqueeze(1).unsqueeze(1)
    absa_2 = torch.tensor(absa_2, dtype=torch.float32).unsqueeze(1).unsqueeze(1)

    labels = torch.tensor(df[aspect].replace({-1: 0, 0: 1, 1: 2}).values, dtype=torch.long)
    
    if method == 'upsample_replacement' and set_name == 'train':
        class_0_indices = [i for i, label in enumerate(labels) if label == 0]
        class_1_indices = [i for i, label in enumerate(labels) if label == 1]
        class_2_indices = [i for i, label in enumerate(labels) if label == 2]

        num_max_class = max(len(class_0_indices), len(class_1_indices), len(class_2_indices))
        resampled_indices = []
        for class_indices in [class_0_indices, class_1_indices, class_2_indices]:
            if len(class_indices) < num_max_class:
                num_upsampling = num_max_class
                resampled_indices.append(np.random.choice(class_indices, num_upsampling, replace=True))
            else:
                resampled_indices.append(class_indices)

        upsampled_indices = np.concatenate(resampled_indices)
        np.random.shuffle(upsampled_indices)

        sent_1 = [sent_1[i] for i in upsampled_indices]
        sent_2 = [sent_2[i] for i in upsampled_indices]
        absa_1 = absa_1[upsampled_indices]
        absa_2 = absa_2[upsampled_indices]
        labels = labels[upsampled_indices]

    sent_1 = [sent.replace("\n", ",").replace(".", " ") for sent in sent_1]
    sent_2 = [sent.replace("\n", ",").replace(".", " ") for sent in sent_2]

    all_sentence_pairs = list(zip(sent_1, sent_2))

    max_seq_length = 128
    total_input_ids = []
    total_input_mask = []
    total_segment_ids = []

    for s1, s2 in tqdm(all_sentence_pairs):
        tokens_a = tokenizer.tokenize(s1)
        tokens_b = tokenizer.tokenize(s2)

        _truncate_seq_pair(tokens_a, tokens_b, max_seq_length - 3) #account for [CLS] [SEP] [SEP]

        tokens = ["[CLS]"] + tokens_a + ["[SEP]"] + tokens_b + ["[SEP]"]
        segment_ids = [0] * (len(tokens_a) + 2) + [1] * (len(tokens_b) + 1)

        input_ids = tokenizer.convert_tokens_to_ids(tokens)
        input_mask = [1] * len(input_ids)

        padding = [0] * (max_seq_length - len(input_ids))
        input_ids += padding
        input_mask += padding
        segment_ids += padding

        assert len(input_ids) == max_seq_length
        assert len(input_mask) == max_seq_length
        assert len(segment_ids) == max_seq_length

        total_input_ids.append(torch.tensor([input_ids], dtype=torch.long).to(device))
        total_input_mask.append(torch.tensor([input_mask], dtype=torch.long).to(device))
        total_segment_ids.append(torch.tensor([segment_ids], dtype=torch.long).to(device))

    assert len(total_input_ids) == len(all_sentence_pairs)
    assert len(total_input_mask) == len(all_sentence_pairs)
    assert len(total_segment_ids) == len(all_sentence_pairs)

    input_ids = torch.cat(total_input_ids, dim=0).to('cpu')
    attention_masks = torch.cat(total_input_mask, dim=0).to('cpu')
    token_type_ids = torch.cat(total_segment_ids, dim=0).to('cpu')

    labels = torch.tensor(labels, dtype=torch.long)

    return null_count, (input_ids, absa_1, absa_2, attention_masks, token_type_ids, labels)

In [6]:
def compute_class_weights(labels):
    class_counts = Counter(labels)
    total_count = sum(class_counts.values())
    class_weights = [total_count / class_counts[i] if i in class_counts else 1.0 for i in range(3)]
    return class_weights

def get_datataset_and_model(method, absa_method, aspect):

    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

    _, train_data = get_dataset(aspect, method, absa_method, tokenizer, 'train')
    
    null_count, val_data = get_dataset(aspect, method, absa_method, tokenizer, 'validation')

    null_count, test_data = get_dataset(aspect, method, absa_method, tokenizer, 'test')

    train_dataset = BeerReviewDataset(*train_data)

    val_dataset = BeerReviewDataset(*val_data)
    
    test_dataset = BeerReviewDataset(*test_data)

    del tokenizer
    torch.cuda.empty_cache()

    if method == 'class-weight':
        class_weights = compute_class_weights([item['labels'] for item in train_dataset])
    else:
        class_weights = None

    return train_dataset, val_dataset, test_dataset, null_count, class_weights

In [7]:
def train(method, absa_method, model_name):
    f1_macro_aspect = 0
    precision_macro_aspect = 0
    recall_macro_aspect = 0
    TFs = (0, 0, 0, 0)

    # gom labels/preds toàn bộ aspects để tính macro-class
    all_labels, all_preds = [], []

    for aspect in aspects:
        print(f'------ Aspect: {aspect}------')
        train_dataset, val_dataset, test_dataset, val_null_count, class_weights = get_datataset_and_model(method, absa_method, aspect)
        config = BERTConfig(absa_method, num_classes=3, class_weights=class_weights)
        model = BERTModel(config).to(device)

        num_epochs=25

        if torch.cuda.device_count() > 1:
            model = nn.DataParallel(model)

        batch_size=64
        lr = 2e-5
        weight_decay = 0.01

        result = train_and_eval_model(
            aspect, method, absa_method, model,
            train_dataset, val_dataset, test_dataset,
            val_null_count,
            batch_size=batch_size, num_epochs=num_epochs,
            lr=lr, weight_decay=weight_decay, patience=5
        )

        # cộng dồn macro-F1 per aspect
        f1_macro_aspect += result['eval_f1_macro']
        precision_macro_aspect += result['eval_precision_macro']
        recall_macro_aspect += result['eval_recall_macro']
        TFs = np.add(TFs, result['eval_total_tf']).tolist()

        # gom labels/preds để tính macro-class flatten
        all_labels.extend(result["eval_labels"])
        all_preds.extend(result["eval_preds"])

        del model, train_dataset, val_dataset
        torch.cuda.empty_cache()

    # --- Macro theo aspect (average đều các aspect) ---
    num_aspects = len(aspects)
    f1_macro_aspect /= num_aspects
    precision_macro_aspect /= num_aspects
    recall_macro_aspect /= num_aspects

    # --- Macro theo class (flatten all aspects) ---
    cm = confusion_matrix(all_labels, all_preds)
    print("Confusion Matrix:\n", cm)
    from sklearn.metrics import precision_recall_fscore_support
    p_macro_class, r_macro_class, f1_macro_class, _ = precision_recall_fscore_support(
        all_labels, all_preds, average="macro", zero_division=0
    )

    # --- Micro (global TP/FP/FN) ---
    total_tp, total_fp, total_tn, total_fn = TFs
    precision_micro = total_tp / (total_tp + total_fp) if (total_tp + total_fp) > 0 else 0
    recall_micro = total_tp / (total_tp + total_fn) if (total_tp + total_fn) > 0 else 0
    f1_micro = (2 * precision_micro * recall_micro) / (precision_micro + recall_micro) if (precision_micro + recall_micro) > 0 else 0

    torch.cuda.empty_cache()

    return {
        # macro-aspect
        "f1_macro_avg": f1_macro_aspect,
        "precision_macro_avg": precision_macro_aspect,
        "recall_macro_avg": recall_macro_aspect,
        # macro-class (flatten)
        "f1_macro_class": f1_macro_class,
        "precision_macro_class": p_macro_class,
        "recall_macro_class": r_macro_class,
        # micro
        "f1_micro": f1_micro,
        "precision_micro": precision_micro,
        "recall_micro": recall_micro,
    }


In [8]:
for model in ["BERT"]:
    print(f'------ Model: {model}------')
    for (method, absa_method) in [
                                  ('class-weight', None), 
                                  ('class-weight', 'min'), 
                                  ('class-weight', 'max'), 
                                  ('class-weight', 'avg'),
                                  ('upsample_replacement', None),
                                  ('upsample_replacement', 'min'),
                                  ('upsample_replacement', 'max'),
                                  ('upsample_replacement', 'avg')
                                 ]:
        result = train(method, absa_method, model)

        if absa_method is None:
            absa_method_str = "None"
        else:
            absa_method_str = absa_method

        eval_metrics = {
            'method': method,
            'absa_method': absa_method_str,

            # --- macro ---
            'f1_macro_avg': result['f1_macro_avg'],
            'precision_macro_avg': result['precision_macro_avg'],
            'recall_macro_avg': result['recall_macro_avg'],

            'f1_macro_class': result['f1_macro_class'],
            'precision_macro_class': result['precision_macro_class'],
            'recall_macro_class': result['recall_macro_class'],

            # --- micro ---
            'f1_micro': result['f1_micro'],
            'precision_micro': result['precision_micro'],
            'recall_micro': result['recall_micro']
        }
        
        print("FINAL: ", eval_metrics)
        
        torch.cuda.empty_cache()


------ Model: BERT------
------ Aspect: appearance------


README.md:   0%|          | 0.00/923 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/211k [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/33.0k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3320 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/420 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/410 [00:00<?, ? examples/s]

100%|██████████| 269/269 [00:00<00:00, 1101.56it/s]


Uploading...:   0%|          | 0.00/438M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.2225795984268188, 'eval_model_preparation_time': 0.0028, 'eval_accuracy': 0.5724907063197026, 'eval_f1_macro': 0.580765789067676, 'eval_precision_macro': 0.5898733178420236, 'eval_recall_macro': 0.5753116238539061, 'eval_f1_micro': 0.5724907063197026, 'eval_precision_micro': 0.5724907063197026, 'eval_recall_micro': 0.5724907063197026, 'eval_total_tf': [154, 115, 423, 115], 'eval_runtime': 0.9726, 'eval_samples_per_second': 276.581, 'eval_steps_per_second': 5.141}
------ Aspect: aroma------


README.md:   0%|          | 0.00/915 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/189k [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/27.7k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/29.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3320 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/420 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/410 [00:00<?, ? examples/s]

100%|██████████| 237/237 [00:00<00:00, 1139.19it/s]


Uploading...:   0%|          | 0.00/438M [00:00<?, ?B/s]

Test results: {'eval_loss': 0.8997212052345276, 'eval_model_preparation_time': 0.0026, 'eval_accuracy': 0.6962025316455697, 'eval_f1_macro': 0.6971578482943287, 'eval_precision_macro': 0.7056563458921602, 'eval_recall_macro': 0.6950129954515919, 'eval_f1_micro': 0.6962025316455697, 'eval_precision_micro': 0.6962025316455697, 'eval_recall_micro': 0.6962025316455697, 'eval_total_tf': [165, 72, 402, 72], 'eval_runtime': 0.8351, 'eval_samples_per_second': 283.786, 'eval_steps_per_second': 4.79}
------ Aspect: palate------


README.md:   0%|          | 0.00/916 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/159k [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/26.2k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/26.9k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3320 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/420 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/410 [00:00<?, ? examples/s]

100%|██████████| 181/181 [00:00<00:00, 1204.38it/s]


Uploading...:   0%|          | 0.00/438M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.4525582790374756, 'eval_model_preparation_time': 0.0029, 'eval_accuracy': 0.5248618784530387, 'eval_f1_macro': 0.5040500240500241, 'eval_precision_macro': 0.5232687232687233, 'eval_recall_macro': 0.5010988800978481, 'eval_f1_micro': 0.5248618784530387, 'eval_precision_micro': 0.5248618784530387, 'eval_recall_micro': 0.5248618784530387, 'eval_total_tf': [95, 86, 276, 86], 'eval_runtime': 0.64, 'eval_samples_per_second': 282.821, 'eval_steps_per_second': 4.688}
------ Aspect: taste------


README.md:   0%|          | 0.00/919 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/313k [00:00<?, ?B/s]

data/validation-00000-of-00001.parquet:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/47.0k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3320 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/420 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/410 [00:00<?, ? examples/s]

100%|██████████| 375/375 [00:00<00:00, 814.59it/s]


Uploading...:   0%|          | 0.00/438M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.130203127861023, 'eval_model_preparation_time': 0.0025, 'eval_accuracy': 0.5786666666666667, 'eval_f1_macro': 0.5838167339701444, 'eval_precision_macro': 0.582633941675396, 'eval_recall_macro': 0.5923398923398923, 'eval_f1_micro': 0.5786666666666667, 'eval_precision_micro': 0.5786666666666667, 'eval_recall_micro': 0.5786666666666667, 'eval_total_tf': [217, 158, 592, 158], 'eval_runtime': 1.3323, 'eval_samples_per_second': 281.47, 'eval_steps_per_second': 4.504}
Confusion Matrix:
 [[187  94  17]
 [110 254  74]
 [ 19 117 190]]
FINAL:  {'method': 'class-weight', 'absa_method': 'None', 'f1_macro_avg': 0.5914475988455433, 'precision_macro_avg': 0.6003580821695758, 'recall_macro_avg': 0.5909408479358096, 'f1_macro_class': 0.599239796313629, 'precision_macro_class': 0.6047217648894708, 'recall_macro_class': 0.5967491800707158, 'f1_micro': 0.5941619585687382, 'precision_micro': 0.5941619585687382, 'recall_micro': 0.5941619585687382}
------ Aspect: appearance------

100%|██████████| 269/269 [00:00<00:00, 1104.71it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.4280954599380493, 'eval_model_preparation_time': 0.0055, 'eval_accuracy': 0.5947955390334573, 'eval_f1_macro': 0.6004473029276727, 'eval_precision_macro': 0.6345451162496091, 'eval_recall_macro': 0.595233765249678, 'eval_f1_micro': 0.5947955390334573, 'eval_precision_micro': 0.5947955390334573, 'eval_recall_micro': 0.5947955390334573, 'eval_total_tf': [160, 109, 429, 109], 'eval_runtime': 1.0184, 'eval_samples_per_second': 264.131, 'eval_steps_per_second': 4.909}
------ Aspect: aroma------


100%|██████████| 237/237 [00:00<00:00, 1085.58it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 0.8267781138420105, 'eval_model_preparation_time': 0.0064, 'eval_accuracy': 0.6286919831223629, 'eval_f1_macro': 0.6317780849030848, 'eval_precision_macro': 0.625236800922494, 'eval_recall_macro': 0.6471734892787525, 'eval_f1_micro': 0.6286919831223629, 'eval_precision_micro': 0.6286919831223629, 'eval_recall_micro': 0.6286919831223629, 'eval_total_tf': [149, 88, 386, 88], 'eval_runtime': 0.9411, 'eval_samples_per_second': 251.842, 'eval_steps_per_second': 4.251}
------ Aspect: palate------


100%|██████████| 181/181 [00:00<00:00, 1087.04it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.1529103517532349, 'eval_model_preparation_time': 0.0059, 'eval_accuracy': 0.5414364640883977, 'eval_f1_macro': 0.5390946502057613, 'eval_precision_macro': 0.5488925302689719, 'eval_recall_macro': 0.5346672782173298, 'eval_f1_micro': 0.5414364640883977, 'eval_precision_micro': 0.5414364640883977, 'eval_recall_micro': 0.5414364640883977, 'eval_total_tf': [98, 83, 279, 83], 'eval_runtime': 0.6792, 'eval_samples_per_second': 266.504, 'eval_steps_per_second': 4.417}
------ Aspect: taste------


100%|██████████| 375/375 [00:00<00:00, 799.45it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.0908002853393555, 'eval_model_preparation_time': 0.0063, 'eval_accuracy': 0.5573333333333333, 'eval_f1_macro': 0.5575860928016902, 'eval_precision_macro': 0.5558878918799158, 'eval_recall_macro': 0.5796397796397796, 'eval_f1_micro': 0.5573333333333333, 'eval_precision_micro': 0.5573333333333333, 'eval_recall_micro': 0.5573333333333333, 'eval_total_tf': [209, 166, 584, 166], 'eval_runtime': 1.3922, 'eval_samples_per_second': 269.359, 'eval_steps_per_second': 4.31}
Confusion Matrix:
 [[204  74  20]
 [131 220  87]
 [ 21 113 192]]
FINAL:  {'method': 'class-weight', 'absa_method': 'min', 'f1_macro_avg': 0.5822265327095522, 'precision_macro_avg': 0.5911405848302477, 'recall_macro_avg': 0.589178578096385, 'f1_macro_class': 0.5863210900602573, 'precision_macro_class': 0.5852382388777113, 'recall_macro_class': 0.5919346395422722, 'f1_micro': 0.5800376647834274, 'precision_micro': 0.5800376647834274, 'recall_micro': 0.5800376647834274}
------ Aspect: appearance-----

100%|██████████| 269/269 [00:00<00:00, 939.33it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.0978481769561768, 'eval_model_preparation_time': 0.0056, 'eval_accuracy': 0.5910780669144982, 'eval_f1_macro': 0.5991810834793787, 'eval_precision_macro': 0.6059003828082955, 'eval_recall_macro': 0.6037186481776161, 'eval_f1_micro': 0.5910780669144982, 'eval_precision_micro': 0.5910780669144982, 'eval_recall_micro': 0.5910780669144982, 'eval_total_tf': [159, 110, 428, 110], 'eval_runtime': 1.0077, 'eval_samples_per_second': 266.951, 'eval_steps_per_second': 4.962}
------ Aspect: aroma------


100%|██████████| 237/237 [00:00<00:00, 1126.37it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 0.8454902768135071, 'eval_model_preparation_time': 0.0056, 'eval_accuracy': 0.6751054852320675, 'eval_f1_macro': 0.6729437229437231, 'eval_precision_macro': 0.6801000165843827, 'eval_recall_macro': 0.6673164392462638, 'eval_f1_micro': 0.6751054852320675, 'eval_precision_micro': 0.6751054852320675, 'eval_recall_micro': 0.6751054852320675, 'eval_total_tf': [160, 77, 397, 77], 'eval_runtime': 0.8874, 'eval_samples_per_second': 267.08, 'eval_steps_per_second': 4.508}
------ Aspect: palate------


100%|██████████| 181/181 [00:00<00:00, 1161.40it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.3360735177993774, 'eval_model_preparation_time': 0.0057, 'eval_accuracy': 0.5027624309392266, 'eval_f1_macro': 0.49776778277527906, 'eval_precision_macro': 0.5095194726342268, 'eval_recall_macro': 0.4971524672247066, 'eval_f1_micro': 0.5027624309392266, 'eval_precision_micro': 0.5027624309392266, 'eval_recall_micro': 0.5027624309392266, 'eval_total_tf': [91, 90, 272, 90], 'eval_runtime': 0.6922, 'eval_samples_per_second': 261.492, 'eval_steps_per_second': 4.334}
------ Aspect: taste------


100%|██████████| 375/375 [00:00<00:00, 814.85it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.4708809852600098, 'eval_model_preparation_time': 0.0065, 'eval_accuracy': 0.6293333333333333, 'eval_f1_macro': 0.6349525393705612, 'eval_precision_macro': 0.6397710193236091, 'eval_recall_macro': 0.6328513828513828, 'eval_f1_micro': 0.6293333333333333, 'eval_precision_micro': 0.6293333333333333, 'eval_recall_micro': 0.6293333333333333, 'eval_total_tf': [236, 139, 611, 139], 'eval_runtime': 1.392, 'eval_samples_per_second': 269.391, 'eval_steps_per_second': 4.31}
Confusion Matrix:
 [[188  96  14]
 [100 255  83]
 [ 20 103 203]]
FINAL:  {'method': 'class-weight', 'absa_method': 'max', 'f1_macro_avg': 0.6012112821422355, 'precision_macro_avg': 0.6088227228376285, 'recall_macro_avg': 0.6002597343749924, 'f1_macro_class': 0.6135910751492921, 'precision_macro_class': 0.6162434286222833, 'recall_macro_class': 0.6119212168488206, 'f1_micro': 0.608286252354049, 'precision_micro': 0.608286252354049, 'recall_micro': 0.608286252354049}
------ Aspect: appearance------


100%|██████████| 269/269 [00:00<00:00, 956.34it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.4789116382598877, 'eval_model_preparation_time': 0.006, 'eval_accuracy': 0.587360594795539, 'eval_f1_macro': 0.5938475094516572, 'eval_precision_macro': 0.6242079588536281, 'eval_recall_macro': 0.5865992270970675, 'eval_f1_micro': 0.587360594795539, 'eval_precision_micro': 0.587360594795539, 'eval_recall_micro': 0.587360594795539, 'eval_total_tf': [158, 111, 427, 111], 'eval_runtime': 1.0094, 'eval_samples_per_second': 266.49, 'eval_steps_per_second': 4.953}
------ Aspect: aroma------


100%|██████████| 237/237 [00:00<00:00, 1155.33it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 0.8095243573188782, 'eval_model_preparation_time': 0.0053, 'eval_accuracy': 0.6413502109704642, 'eval_f1_macro': 0.6450582137012216, 'eval_precision_macro': 0.6423976608187134, 'eval_recall_macro': 0.6739766081871345, 'eval_f1_micro': 0.6413502109704642, 'eval_precision_micro': 0.6413502109704642, 'eval_recall_micro': 0.6413502109704642, 'eval_total_tf': [152, 85, 389, 85], 'eval_runtime': 0.8847, 'eval_samples_per_second': 267.881, 'eval_steps_per_second': 4.521}
------ Aspect: palate------


100%|██████████| 181/181 [00:00<00:00, 1217.57it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.3596549034118652, 'eval_model_preparation_time': 0.0051, 'eval_accuracy': 0.5359116022099447, 'eval_f1_macro': 0.5304675716440422, 'eval_precision_macro': 0.5515315315315316, 'eval_recall_macro': 0.5227707067232351, 'eval_f1_micro': 0.5359116022099447, 'eval_precision_micro': 0.5359116022099447, 'eval_recall_micro': 0.5359116022099447, 'eval_total_tf': [97, 84, 278, 84], 'eval_runtime': 0.6734, 'eval_samples_per_second': 268.784, 'eval_steps_per_second': 4.455}
------ Aspect: taste------


100%|██████████| 375/375 [00:00<00:00, 844.27it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.1132190227508545, 'eval_model_preparation_time': 0.0053, 'eval_accuracy': 0.5786666666666667, 'eval_f1_macro': 0.5822052164337599, 'eval_precision_macro': 0.585040088910058, 'eval_recall_macro': 0.5958675458675459, 'eval_f1_micro': 0.5786666666666667, 'eval_precision_micro': 0.5786666666666667, 'eval_recall_micro': 0.5786666666666667, 'eval_total_tf': [217, 158, 592, 158], 'eval_runtime': 1.4003, 'eval_samples_per_second': 267.804, 'eval_steps_per_second': 4.285}
Confusion Matrix:
 [[202  80  16]
 [131 228  79]
 [ 24 108 194]]
FINAL:  {'method': 'class-weight', 'absa_method': 'avg', 'f1_macro_avg': 0.5878946278076702, 'precision_macro_avg': 0.6007943100284827, 'recall_macro_avg': 0.5948035219687458, 'f1_macro_class': 0.5938820158353718, 'precision_macro_class': 0.5950611768085817, 'recall_macro_class': 0.5978307729128818, 'f1_micro': 0.5875706214689266, 'precision_micro': 0.5875706214689266, 'recall_micro': 0.5875706214689266}
------ Aspect: appearance----

100%|██████████| 269/269 [00:00<00:00, 1071.21it/s]


Uploading...:   0%|          | 0.00/438M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.3444275856018066, 'eval_model_preparation_time': 0.0026, 'eval_accuracy': 0.6319702602230484, 'eval_f1_macro': 0.6376917718919112, 'eval_precision_macro': 0.6597037465458517, 'eval_recall_macro': 0.6285415245889218, 'eval_f1_micro': 0.6319702602230484, 'eval_precision_micro': 0.6319702602230484, 'eval_recall_micro': 0.6319702602230484, 'eval_total_tf': [170, 99, 439, 99], 'eval_runtime': 0.957, 'eval_samples_per_second': 281.093, 'eval_steps_per_second': 5.225}
------ Aspect: aroma------


100%|██████████| 237/237 [00:00<00:00, 1208.60it/s]


Uploading...:   0%|          | 0.00/438M [00:00<?, ?B/s]

Test results: {'eval_loss': 0.8431817293167114, 'eval_model_preparation_time': 0.0029, 'eval_accuracy': 0.679324894514768, 'eval_f1_macro': 0.6809871649443843, 'eval_precision_macro': 0.6877335299901671, 'eval_recall_macro': 0.6799057829759584, 'eval_f1_micro': 0.679324894514768, 'eval_precision_micro': 0.679324894514768, 'eval_recall_micro': 0.679324894514768, 'eval_total_tf': [161, 76, 398, 76], 'eval_runtime': 0.8442, 'eval_samples_per_second': 280.741, 'eval_steps_per_second': 4.738}
------ Aspect: palate------


100%|██████████| 181/181 [00:00<00:00, 1143.10it/s]


Uploading...:   0%|          | 0.00/438M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.6310354471206665, 'eval_model_preparation_time': 0.0029, 'eval_accuracy': 0.49171270718232046, 'eval_f1_macro': 0.4697459086993971, 'eval_precision_macro': 0.4967643467643468, 'eval_recall_macro': 0.46621182586094867, 'eval_f1_micro': 0.49171270718232046, 'eval_precision_micro': 0.49171270718232046, 'eval_recall_micro': 0.49171270718232046, 'eval_total_tf': [89, 92, 270, 92], 'eval_runtime': 0.6466, 'eval_samples_per_second': 279.942, 'eval_steps_per_second': 4.64}
------ Aspect: taste------


100%|██████████| 375/375 [00:00<00:00, 798.30it/s]


Uploading...:   0%|          | 0.00/438M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.312873363494873, 'eval_model_preparation_time': 0.0027, 'eval_accuracy': 0.6053333333333333, 'eval_f1_macro': 0.6118374951107654, 'eval_precision_macro': 0.6102344654506632, 'eval_recall_macro': 0.614008764008764, 'eval_f1_micro': 0.6053333333333333, 'eval_precision_micro': 0.6053333333333333, 'eval_recall_micro': 0.6053333333333333, 'eval_total_tf': [227, 148, 602, 148], 'eval_runtime': 1.3327, 'eval_samples_per_second': 281.391, 'eval_steps_per_second': 4.502}
Confusion Matrix:
 [[181  97  20]
 [ 91 272  75]
 [ 13 119 194]]
FINAL:  {'method': 'upsample_replacement', 'absa_method': 'None', 'f1_macro_avg': 0.6000655851616145, 'precision_macro_avg': 0.6136090221877571, 'recall_macro_avg': 0.5971669743586482, 'f1_macro_class': 0.6130978515568898, 'precision_macro_class': 0.6212483484317275, 'recall_macro_class': 0.6078263803618311, 'f1_micro': 0.6092278719397364, 'precision_micro': 0.6092278719397364, 'recall_micro': 0.6092278719397364}
------ Aspect: appear

100%|██████████| 269/269 [00:00<00:00, 969.55it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.5743340253829956, 'eval_model_preparation_time': 0.0059, 'eval_accuracy': 0.6319702602230484, 'eval_f1_macro': 0.6366052873229906, 'eval_precision_macro': 0.6658898532090431, 'eval_recall_macro': 0.6254754868530726, 'eval_f1_micro': 0.6319702602230484, 'eval_precision_micro': 0.6319702602230484, 'eval_recall_micro': 0.6319702602230484, 'eval_total_tf': [170, 99, 439, 99], 'eval_runtime': 1.0141, 'eval_samples_per_second': 265.266, 'eval_steps_per_second': 4.931}
------ Aspect: aroma------


100%|██████████| 237/237 [00:00<00:00, 1221.76it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.0787434577941895, 'eval_model_preparation_time': 0.0054, 'eval_accuracy': 0.6751054852320675, 'eval_f1_macro': 0.6662709408195722, 'eval_precision_macro': 0.6779634974079419, 'eval_recall_macro': 0.6630929174788824, 'eval_f1_micro': 0.6751054852320675, 'eval_precision_micro': 0.6751054852320675, 'eval_recall_micro': 0.6751054852320675, 'eval_total_tf': [160, 77, 397, 77], 'eval_runtime': 0.8821, 'eval_samples_per_second': 268.673, 'eval_steps_per_second': 4.535}
------ Aspect: palate------


100%|██████████| 181/181 [00:00<00:00, 1224.59it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.6577961444854736, 'eval_model_preparation_time': 0.0052, 'eval_accuracy': 0.5303867403314917, 'eval_f1_macro': 0.5045690957293166, 'eval_precision_macro': 0.5472283272283273, 'eval_recall_macro': 0.5033348622099911, 'eval_f1_micro': 0.5303867403314917, 'eval_precision_micro': 0.5303867403314917, 'eval_recall_micro': 0.5303867403314917, 'eval_total_tf': [96, 85, 277, 85], 'eval_runtime': 0.6742, 'eval_samples_per_second': 268.484, 'eval_steps_per_second': 4.45}
------ Aspect: taste------


100%|██████████| 375/375 [00:00<00:00, 861.54it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.3693463802337646, 'eval_model_preparation_time': 0.0057, 'eval_accuracy': 0.5973333333333334, 'eval_f1_macro': 0.604937173377391, 'eval_precision_macro': 0.6054346884621139, 'eval_recall_macro': 0.6082642082642084, 'eval_f1_micro': 0.5973333333333334, 'eval_precision_micro': 0.5973333333333334, 'eval_recall_micro': 0.5973333333333334, 'eval_total_tf': [224, 151, 599, 151], 'eval_runtime': 1.3944, 'eval_samples_per_second': 268.938, 'eval_steps_per_second': 4.303}
Confusion Matrix:
 [[165 114  19]
 [ 67 273  98]
 [ 13 101 212]]
FINAL:  {'method': 'upsample_replacement', 'absa_method': 'min', 'f1_macro_avg': 0.6030956243123176, 'precision_macro_avg': 0.6241290915768565, 'recall_macro_avg': 0.6000418687015386, 'f1_macro_class': 0.6148986267594312, 'precision_macro_class': 0.6257575056531158, 'recall_macro_class': 0.6090952316223065, 'f1_micro': 0.6120527306967984, 'precision_micro': 0.6120527306967984, 'recall_micro': 0.6120527306967984}
------ Aspect: appear

100%|██████████| 269/269 [00:00<00:00, 973.19it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.3874446153640747, 'eval_model_preparation_time': 0.0059, 'eval_accuracy': 0.5799256505576208, 'eval_f1_macro': 0.5830037649727081, 'eval_precision_macro': 0.6207556193208991, 'eval_recall_macro': 0.5746296506781845, 'eval_f1_micro': 0.5799256505576208, 'eval_precision_micro': 0.5799256505576208, 'eval_recall_micro': 0.5799256505576208, 'eval_total_tf': [156, 113, 425, 113], 'eval_runtime': 1.0108, 'eval_samples_per_second': 266.129, 'eval_steps_per_second': 4.947}
------ Aspect: aroma------


100%|██████████| 237/237 [00:00<00:00, 1150.72it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 0.991628110408783, 'eval_model_preparation_time': 0.0062, 'eval_accuracy': 0.6413502109704642, 'eval_f1_macro': 0.6365410283568851, 'eval_precision_macro': 0.6455957423699359, 'eval_recall_macro': 0.6414879792072774, 'eval_f1_micro': 0.6413502109704642, 'eval_precision_micro': 0.6413502109704642, 'eval_recall_micro': 0.6413502109704642, 'eval_total_tf': [152, 85, 389, 85], 'eval_runtime': 0.9043, 'eval_samples_per_second': 262.086, 'eval_steps_per_second': 4.423}
------ Aspect: palate------


100%|██████████| 181/181 [00:00<00:00, 1045.30it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.385151982307434, 'eval_model_preparation_time': 0.0058, 'eval_accuracy': 0.5082872928176796, 'eval_f1_macro': 0.47982843955066184, 'eval_precision_macro': 0.516047764671618, 'eval_recall_macro': 0.4782803959790544, 'eval_f1_micro': 0.5082872928176796, 'eval_precision_micro': 0.5082872928176796, 'eval_recall_micro': 0.5082872928176796, 'eval_total_tf': [92, 89, 273, 89], 'eval_runtime': 0.679, 'eval_samples_per_second': 266.58, 'eval_steps_per_second': 4.418}
------ Aspect: taste------


100%|██████████| 375/375 [00:00<00:00, 763.04it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 0.9887453317642212, 'eval_model_preparation_time': 0.0058, 'eval_accuracy': 0.608, 'eval_f1_macro': 0.6128643179345606, 'eval_precision_macro': 0.6083744313381593, 'eval_recall_macro': 0.6211634711634711, 'eval_f1_micro': 0.608, 'eval_precision_micro': 0.608, 'eval_recall_micro': 0.608, 'eval_total_tf': [228, 147, 603, 147], 'eval_runtime': 1.3967, 'eval_samples_per_second': 268.497, 'eval_steps_per_second': 4.296}
Confusion Matrix:
 [[170 110  18]
 [ 90 256  92]
 [ 19 105 202]]
FINAL:  {'method': 'upsample_replacement', 'absa_method': 'max', 'f1_macro_avg': 0.5780593877037039, 'precision_macro_avg': 0.597693389425153, 'recall_macro_avg': 0.5788903742569969, 'f1_macro_class': 0.595246643929717, 'precision_macro_class': 0.6000931033291831, 'recall_macro_class': 0.5915255287809859, 'f1_micro': 0.591337099811676, 'precision_micro': 0.591337099811676, 'recall_micro': 0.591337099811676}
------ Aspect: appearance------


100%|██████████| 269/269 [00:00<00:00, 991.31it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.3246126174926758, 'eval_model_preparation_time': 0.0053, 'eval_accuracy': 0.6171003717472119, 'eval_f1_macro': 0.6208961270458597, 'eval_precision_macro': 0.6572881982981872, 'eval_recall_macro': 0.61175645980147, 'eval_f1_micro': 0.6171003717472119, 'eval_precision_micro': 0.6171003717472119, 'eval_recall_micro': 0.6171003717472119, 'eval_total_tf': [166, 103, 435, 103], 'eval_runtime': 1.0078, 'eval_samples_per_second': 266.92, 'eval_steps_per_second': 4.961}
------ Aspect: aroma------


100%|██████████| 237/237 [00:00<00:00, 1087.16it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 0.9715647101402283, 'eval_model_preparation_time': 0.0057, 'eval_accuracy': 0.6540084388185654, 'eval_f1_macro': 0.6541118448236128, 'eval_precision_macro': 0.652824092600003, 'eval_recall_macro': 0.6599252761533463, 'eval_f1_micro': 0.6540084388185654, 'eval_precision_micro': 0.6540084388185654, 'eval_recall_micro': 0.6540084388185654, 'eval_total_tf': [155, 82, 392, 82], 'eval_runtime': 0.8842, 'eval_samples_per_second': 268.052, 'eval_steps_per_second': 4.524}
------ Aspect: palate------


100%|██████████| 181/181 [00:00<00:00, 1049.56it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 1.676090955734253, 'eval_model_preparation_time': 0.0054, 'eval_accuracy': 0.5414364640883977, 'eval_f1_macro': 0.5171527424975252, 'eval_precision_macro': 0.5571981497215143, 'eval_recall_macro': 0.5128330084470435, 'eval_f1_micro': 0.5414364640883977, 'eval_precision_micro': 0.5414364640883977, 'eval_recall_micro': 0.5414364640883977, 'eval_total_tf': [98, 83, 279, 83], 'eval_runtime': 0.6765, 'eval_samples_per_second': 267.539, 'eval_steps_per_second': 4.434}
------ Aspect: taste------


100%|██████████| 375/375 [00:00<00:00, 776.19it/s]


Uploading...:   0%|          | 0.00/876M [00:00<?, ?B/s]

Test results: {'eval_loss': 0.9725877046585083, 'eval_model_preparation_time': 0.0053, 'eval_accuracy': 0.5813333333333334, 'eval_f1_macro': 0.5878543141909317, 'eval_precision_macro': 0.5832074748967141, 'eval_recall_macro': 0.5948791448791448, 'eval_f1_micro': 0.5813333333333334, 'eval_precision_micro': 0.5813333333333334, 'eval_recall_micro': 0.5813333333333334, 'eval_total_tf': [218, 157, 593, 157], 'eval_runtime': 1.3914, 'eval_samples_per_second': 269.52, 'eval_steps_per_second': 4.312}
Confusion Matrix:
 [[180 102  16]
 [ 87 259  92]
 [ 17 111 198]]
FINAL:  {'method': 'upsample_replacement', 'absa_method': 'avg', 'f1_macro_avg': 0.5950037571394823, 'precision_macro_avg': 0.6126294788791047, 'recall_macro_avg': 0.5948484723202512, 'f1_macro_class': 0.60478991624757, 'precision_macro_class': 0.6098634846633808, 'recall_macro_class': 0.6009043365803367, 'f1_micro': 0.5998116760828626, 'precision_micro': 0.5998116760828626, 'recall_micro': 0.5998116760828626}
